name: CI/CD for React App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      
      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: check repo
        run:  ls  

      - name: Deploy with gh-pages
        run: |
             git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
             npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
