name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # or use the version of Node.js you need

      - name: Install dependencies
        run: npm install

      - name: Build the Vite app
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is automatically provided by GitHub Actions
        run: |
          git config --global user.name 'modibhargav98'
          git config --global user.email 'modibhargav1998@gmail.com'
          npm run deploy
